### ISSUE TITLE
 response headers 

### ISSUE THREAD

**Issue by 3052** [suchipi/webview#7]
posting again since previous issue was closed in error. if I want to open a webview for example:

http://example.com

I can to be able to capture the response headers from that request. so for example if I use:

  --url string
        instead of serving files, load this url

I want the tool to output the response headers somehow. I dont have control over the JS on that page, so Fetch is not an option here

**Comment by suchipi** [comment]
I closed the previous issue on purpose because the question was too vague. Don't open new issues about the same thing. 

This is the wrong tool for what you're trying to do. Use [Selenium](https://www.selenium.dev/) or [Puppeteer](https://pptr.dev/) instead.

**Comment by suchipi** [comment]
or [curl](https://curl.se/)

**Comment by 3052** [comment]
you seem to be suffering from "confidently wrong" syndrome. the page in question absolutely cannot be capture with cURL, as it requires special headers that are generated by JavaScript.

> Don't open new issues about the same thing.

dont slam issues closed without even giving the person a chance to respond. its incredibly rude. IF you had made your comment, and IF I had not responded for a day or something, sure go ahead and close. but you didn't do that, you just immediately closed the issue. if you want respect, give repsect.

**Comment by suchipi** [comment]
don't lecture me on github issue etiquette when you're putting so little effort into your issue descriptions. with such low-effort vague drive-bys like that, you should expect to be ignored outright; me taking time to reply at it *at all* is an act of benevolence.

and don't call me "confidently wrong" when you haven't even begun to give me the __bare minimum__ background info needed to understand your use-case. I can't read your mind. explaining yourself and being thorough is basic internet etiquette.

Selenium or Puppeteer will probably work for whatever it is you're trying to do that you won't tell me about. You're lucky to even get that recommendation. I'm done talking about this.
